export default {
    ReceivingClientID: { type: Number, required: true },
    ReceivingPaymentID: { type: String, required: true },
    ReceivingName: { type: String, required: true },
    ReceivingEmail: { type: String, required: true },
    ReceivingPhone: { type: String, required: true },
    SendingClientID: { type: Number, required: true },
    SendingPaymentID: { type: String, required: true },
    SenderName: { type: String, required: true },
    SenderEmail: { type: String, required: true },
    SenderPhone: { type: String, required: true },
    TransactionID: { type: Number, default: '00000' },
    TransactionDate: { type: Date, required: true, default: Date.now() },
    TransactionType: { type: String, required: true, default: "Deposit" },
    TransactionAmount: { type: Number, required: true },
    TransactionDescription: { type: String, required: true, default: "No description provided." },
    TransactionStatus: { type: String, required: true, default: "Pending" },
};
