export default {
    ReceivingClientID: { type: Number, required: true, default: 0},
    ReceivingPaymentID: { type: String, required: true, default: 'example@pp'},
    ReceivingName: { type: String, required: true },
    ReceivingEmail: { type: String, required: true },
    ReceivingPhone: { type: String, required: true, length: 10},
    SendingClientID: { type: Number, required: true },
    SendingPaymentID: { type: String, required: true, unique: true},
    SenderName: { type: String, required: true },
    TransactionMethod: { type: String, default: "PaisaPay Wallet", index: true },
    SenderEmail: { type: String, required: true },
    SenderPhone: { type: String, required: true },
    TransactionID: { type: Number, default: '00000', unique: true},
    TransactionDate: { type: Date, required: true, default: Date.now(), index: true },
    TransactionType: { type: String, required: true, default: "Deposit" },
    TransactionAmount: { type: Number, required: true },
    TransactionDescription: { type: String, required: true, default: "No description provided." },
    TransactionStatus: { type: String, required: true, default: "Pending" },
};
