export default {
	ClientID: { type: Number, required: true, unique: true },
	Name: { type: String, required: true },
	Email: { type: String, required: true, unique: true },
	DOB: { type: Date, required: true, index: true },
	PaymentID: { type: String, required: true, unique: true },
	Balance: { type: Number, required: true, default: 0 },
	PhoneNumber: { type: Number, required: true, unique: true },
	Password: { type: String, required: true, minlength: 8 },
	TransactionPIN : { type: String, required: true, minlength: 4 },
	National_ID_Type: { type: String, required: true, index: true },
	National_ID_Number: { type: String, required: true, unique: true },
	LastFourDigitsOfIDNumber: { type: String, required: true, unique: true },
	ProfilePicturePath: { type: String, required: true },
	ProfilePicSize: { type: String, required: true, default: '0 KB', index: true },
	ProfilePicFileName: { type: String, required: true, unique: true },
	DateCreated: { type: Date, required: true, default: Date.now(), index: true },
	AccountStatus: { type: String, required: true, default: 'Active', enum: ['Active', 'Suspended', 'Disabled', 'Deleted'] },
	AccountType: { type: String, required: true, default: 'Client' },
	LastLoginTime: { type: Date, required: true, default: Date.now() },
	LastLoginIP: { type: String, required: true, default: '192.168.0.1' },
	LastLoginClientDetails: { type: Object, required: true },
	LastLoginToken: { type: String, required: true, default: '' },
}; // export the client account data model
