export default {
	ReceivingClientID: { type: Number, required: true, default: 0, minlength: 15, unique: false },
	ReceivingPaymentID: { type: String, required: true, default: "example@pp", unique: false },
	ReceivingName: { type: String, required: true, default: "guest", unique: false },
	ReceivingEmail: { type: String, required: true, unique: false, default: "example@example.com" },
	ReceivingPhone: { type: String, required: true, minlength: 10, maxlength: 10, default: 0, unique: false },
	SendingClientID: { type: Number, required: true, default: 0, minlength: 15, unique: false },
	SendingPaymentID: { type: String, required: true, default: "example@pp", unique: false },
	SenderName: { type: String, required: true, default: "guest", unique: false },
	TransactionMethod: { type: String, default: "PaisaPay Wallet", unique: false, enum: ["PaisaPay Wallet"] },
	SenderEmail: { type: String, required: true, unique: false, default: "example@example.com" },
	SenderPhone: { type: String, required: true, minlength: 10, maxlength: 10, default: 0, unique: false },
	TransactionID: { type: Number, default: "00000", unique: true, required: true, minlength: 15 },
	TransactionDate: { type: Date, required: true, default: Date.now(), unique: false },
	TransactionType: { type: String, default: "P2P Deposit", unique: false },
	TransactionAmount: { type: Number, required: true, default: 0, unique: false, min: 0 },
	TransactionDescription: { type: String, required: true, default: "No description provided.", unique: false },
	TransactionStatus: {
		type: String,
		required: true,
		default: "Pending",
		unique: false,
	},
};
