export default {
	ReceivingClientID: { type: Number, required: true, default: 0, min: 20, max: 20, unique: false },
	ReceivingPaymentID: { type: String, required: true, default: 'example@pp', unique: false },
	ReceivingName: { type: String, required: true, default: 'guest', unique: false },
	ReceivingEmail: { type: String, required: true, unique: false, default: 'example@example.com' },
	ReceivingPhone: { type: String, required: true, minlength: 10, maxlength: 10, default: 0, unique: false },
	SendingClientID: { type: Number, required: true, default: 0, min: 20, max: 20, unique: false },
	SendingPaymentID: { type: String, required: true, default: 'example@pp', unique: false },
	SenderName: { type: String, required: true, default: 'guest', unique: false },
	TransactionMethod: { type: String, default: 'PaisaPay Wallet', enum: ['PaisaPay Wallet', 'Other'], unique: false },
	SenderEmail: { type: String, required: true, unique: false, default: 'example@example.com' },
	SenderPhone: { type: String, required: true, minlength: 10, maxlength: 10, default: 0, unique: false },
	TransactionID: { type: Number, default: '00000', unique: true, required: true, min: 18, max: 18 },
	TransactionDate: { type: Date, required: true, default: Date.now(), unique: false},
	TransactionType: { type: String, default: 'P2P Deposit', enum: ['P2P Deposit', 'P2P Withdrawal', 'P2P Transfer', 'P2P Payment'], unique: false },
	TransactionAmount: { type: Number, required: true, default: 0, unique: false, min: 0 },
	TransactionDescription: { type: String, required: true, default: 'No description provided.', unique: false },
	TransactionStatus: { type: String, required: true, default: 'Pending', enum: ['Pending', 'Transaction Success', 'Transaction Failed'], unique: false },
};
