export default {
	UserClientID: { type: Number, required: true, default: 0, minlength: 20, unique: false },
	UserPaymentID: { type: String, required: true, default: "example@pp", unique: false },
	UserName: { type: String, required: true, default: "guest", unique: false },
	UserEmail: { type: String, required: true, unique: false, default: "example@example.com" },
	UserPhone: { type: String, required: true, length: 10, default: 0, unique: false },
	TransactionID: { type: String, default: "00000", required: true, unique: true, minlength: 15, maxlength:28 },
	TransactionMethod: { type: String, required: true, default: "Unknown", enum: ["Unknown", "PaisaPay Wallet", "Other"], unique: false },
	TransactionDate: { type: Date, required: true, default: Date.now(), unique: false },
	TransactionAmount: { type: Number, required: true, default: 0, unique: false, min: 0 },
	TransactionStatus: { type: String, required: true, default: "Success", enum: ["Success", "Pending", "Failed", "Cancelled", "Processing"] },
	TransactionFee: { type: Number, required: true, default: 0, unique: false, min: 0 },
	BankName: { type: String, required: true, default: "Unknown", unique: false },
	BankAccountHolderName: { type: String, required: true, default: "Unknown", unique: false },
	BankAccountNumber: { type: Number, required: true, default: "Unknown", unique: false },
	BankAccountType: { type: String, required: true, default: "Savings", enum: ["Savings", "Current"], unique: false },
	BankAccountBranch: { type: String, required: true, default: "Unknown", unique: false },
	IFSC_Code: { type: String, required: true, default: "Unknown", unique: false },
};
